name: aid_first
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+1
  firebase_auth: ^0.15.5+2
  firebase_storage: ^3.1.3
  firebase_database: ^3.1.1
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.24+1
  location: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/login.jpg
    - assets/current_location.png